version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 7777:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  zhu:
    image: bougoss95/privatezhu
    ports:
      - 8081:80

  tim:
    image: tim95/tim95_myprivaterepo
    ports:
      - 8082:80

  caillou:
    image: caillouesieeit/myrepo
    ports:
      - 8083:80

volumes:
  wordpress:
  db: